//! Tests for the infrastructure layer.
//!
//! These tests exercise the two pieces that do not require a live
//! PostgreSQL connection:
//!
//! 1. The `0001_create_users.sql` migration file content (the schema
//!    that downstream tasks will apply). The leading doc comment is
//!    stripped before assertion so the tests anchor on the `CREATE
//!    TABLE` block, not on keywords in the header.
//! 2. The `UserRow` -> `User` conversion, including the role parsing
//!    path.
//!
//! A live-database round-trip test is included below as `#[ignore]` so
//! that `cargo test -p user` stays green without a connection. Run it
//! with:
//!
//! ```text
//! cargo test -p user -- --ignored
//! ```

use std::convert::TryFrom;
use std::fs;
use std::path::PathBuf;

use crate::domain::{DomainError, Role, User, UserRepository};

use super::row::UserRow;

fn migration_path() -> PathBuf {
    // CARGO_MANIFEST_DIR is the directory of `Cargo.toml` for the
    // `user` crate, i.e. `lib/crates/user/`.
    let manifest_dir = env!("CARGO_MANIFEST_DIR");
    PathBuf::from(manifest_dir)
        .join("migrations")
        .join("0001_create_users.sql")
}

fn load_migration() -> String {
    fs::read_to_string(migration_path())
        .expect("migration file lib/crates/user/migrations/0001_create_users.sql must exist")
}

/// Slice the migration down to the `CREATE TABLE users (...)` body so
/// the tests assert against the schema, not against the doc-comment
/// header that shares the same keywords.
fn create_table_block() -> String {
    let sql = load_migration();
    let start = sql
        .find("CREATE TABLE")
        .expect("migration must contain a CREATE TABLE statement");
    // Find the matching `);` that closes the `CREATE TABLE`. The
    // migration has a single CREATE TABLE; if that ever changes, this
    // helper should be updated to take a table name.
    let close = sql[start..]
        .find(");")
        .expect("CREATE TABLE body must be terminated by `);`");
    sql[start..start + close + 2].to_string()
}

#[test]
fn migration_creates_users_table() {
    let block = create_table_block();
    assert!(
        block.contains("CREATE TABLE") && block.contains("users"),
        "CREATE TABLE block must define a users table; got:\n{block}"
    );
}

#[test]
fn migration_has_id_column_with_primary_key() {
    let block = create_table_block();
    assert!(
        block.contains("id") && block.contains("GENERATED BY DEFAULT AS IDENTITY"),
        "id must be an IDENTITY column; got:\n{block}"
    );
    assert!(
        block.contains("PRIMARY KEY"),
        "users table must declare a PRIMARY KEY; got:\n{block}"
    );
}

#[test]
fn migration_has_required_columns() {
    let block = create_table_block();
    let upper = block.to_uppercase();

    // The brief requires these six columns. We assert the column name
    // appears inside the users table definition, in any case the file
    // may use.
    for required in [
        "id INTEGER",
        "code TEXT",
        "name TEXT",
        "role TEXT",
        "active BOOLEAN",
        "password TEXT",
    ] {
        assert!(
            upper.contains(&required.to_uppercase()),
            "users table must include `{required}`; got:\n{block}"
        );
    }
}

#[test]
fn migration_makes_code_unique_and_not_null() {
    let block = create_table_block();
    let upper = block.to_uppercase();
    assert!(
        upper.contains("UNIQUE"),
        "code must be UNIQUE; got:\n{block}"
    );
    // The brief requires `code` to be unique AND non-null. We assert
    // NOT NULL appears in the CREATE TABLE body and that a UNIQUE
    // constraint targets `code` (either inline or as a separate
    // constraint).
    assert!(
        upper.contains("NOT NULL"),
        "users table must declare NOT NULL constraints; got:\n{block}"
    );
    assert!(
        block.contains("UNIQUE (code)")
            || block.contains("UNIQUE(\"code\")")
            || block.contains("UNIQUE  (code)"),
        "expected a UNIQUE constraint on code; got:\n{block}"
    );
}

#[test]
fn migration_has_role_check_constraint() {
    let block = create_table_block();
    let upper = block.to_uppercase();
    assert!(
        upper.contains("CHECK"),
        "users table must declare a CHECK constraint; got:\n{block}"
    );
    // The CHECK must mention `role` and the three allowed values.
    assert!(
        upper.contains("ROLE"),
        "CHECK constraint must apply to `role`; got:\n{block}"
    );
    for value in ["'root'", "'admin'", "'general'"] {
        assert!(
            upper.contains(&value.to_uppercase()),
            "role CHECK must list {value}; got:\n{block}"
        );
    }
}

#[test]
fn row_converts_to_user_for_each_known_role() {
    for (role, as_str) in [
        (Role::Root, "root"),
        (Role::Admin, "admin"),
        (Role::General, "general"),
    ] {
        let row = UserRow {
            id: 1,
            code: format!("user-{as_str}"),
            name: "Alice".to_string(),
            role: as_str.to_string(),
            active: true,
            password: "argon-phc".to_string(),
        };
        let user: User = row.try_into().expect("known role must convert");
        assert_eq!(user.id, 1);
        assert_eq!(user.code, format!("user-{as_str}"));
        assert_eq!(user.name, "Alice");
        assert_eq!(user.role, role);
        assert!(user.active);
        assert_eq!(user.password_hash(), "argon-phc");
    }
}

#[test]
fn row_with_unknown_role_fails_to_convert() {
    let row = UserRow {
        id: 2,
        code: "u2".to_string(),
        name: "Bob".to_string(),
        role: "superuser".to_string(),
        active: true,
        password: "argon-phc".to_string(),
    };
    let err = User::try_from(row).expect_err("unknown role must be rejected");
    assert!(
        matches!(err, DomainError::InvalidRole(ref s) if s == "superuser"),
        "expected InvalidRole(\"superuser\"), got {err:?}"
    );
}

#[test]
fn user_password_hash_accessor_returns_the_hash() {
    let row = UserRow {
        id: 3,
        code: "u3".to_string(),
        name: "Carol".to_string(),
        role: "root".to_string(),
        active: true,
        password: "$argon2id$v=19$secret".to_string(),
    };
    let user: User = row.try_into().expect("known role must convert");
    assert_eq!(user.password_hash(), "$argon2id$v=19$secret");
}

#[test]
#[ignore = "requires a live PostgreSQL configured via DATABASE_URL"]
fn live_database_create_then_find_then_deactivate() {
    // The actual round-trip test is wired up here so that downstream
    // tasks / reviewers can opt in with `cargo test -p user -- --ignored`.
    // It is gated because the CI environment for this task has no
    // PostgreSQL.
    let url = match std::env::var("DATABASE_URL") {
        Ok(v) if !v.is_empty() => v,
        _ => panic!("DATABASE_URL must be set to run ignored tests"),
    };
    let runtime = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .expect("runtime");
    runtime.block_on(async move {
        let pool = sqlx::PgPool::connect(&url)
            .await
            .expect("connect to PostgreSQL");

        let repo = super::user_repo::UserRepo::new(pool);

        // Use a code unique to this run to avoid clashing with other
        // state in the database.
        let unique = format!("task4-{}", nanosecond_suffix());
        let new = crate::domain::UserNew {
            code: unique.clone(),
            name: "Task Four".to_string(),
            role: Role::Admin,
            password_hash: "$argon2id$v=19$placeholder".to_string(),
            active: true,
        };
        let created = repo.create(new).await.expect("create");
        assert_eq!(created.code, unique);
        assert!(created.active);

        let fetched_by_id = repo
            .find_by_id(created.id)
            .await
            .expect("find_by_id");
        assert_eq!(fetched_by_id.id, created.id);

        let fetched_by_code = repo
            .find_by_code(&unique)
            .await
            .expect("find_by_code");
        assert_eq!(fetched_by_code.id, created.id);

        let list = repo.list().await.expect("list");
        assert!(list.iter().any(|u| u.id == created.id));

        let update = crate::domain::UserUpdate {
            id: created.id,
            name: Some("Task Four Renamed".to_string()),
            ..Default::default()
        };
        let updated = repo.update(update).await.expect("update");
        assert_eq!(updated.name, "Task Four Renamed");

        let deactivated = repo
            .deactivate(created.id)
            .await
            .expect("deactivate");
        assert!(!deactivated.active);
    });
}

/// Small helper that does not require pulling the `uuid` crate into
/// the workspace just for the ignored test. Formats the current
/// `SystemTime` nanosecond counter as a lowercase hex string, which
/// is unique enough to avoid clashing with other rows in the same
/// database across runs of the ignored test.
fn nanosecond_suffix() -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_nanos())
        .unwrap_or(0);
    format!("{nanos:x}")
}
