-- 0001_create_missions.sql
--
-- Single migration for the `mission` crate that owns the
-- `Mission` aggregate. Assignees live in their own migration
-- so the per-mission UNIQUE constraint and `ON DELETE CASCADE`
-- FK are co-located with the `assignees` table definition.
--
-- Layout:
--   * `missions`
--       - `id`              surrogate primary key.
--       - `project_code`    caller-chosen; not a FK (no FK to
--                            `projects.code` because projects uses
--                            INTEGER ids and the spec keeps the
--                            mission / project relationship
--                            resolved at the usecase via
--                            `ProjectLookup`).
--       - `mission_kind`    text discriminant ('crf', 'sdtm',
--                            'adam', 'tfl') — belt-and-braces
--                            CHECK against out-of-band inserts.
--       - `mission_code`    caller-chosen stable identifier.
--       - `created_at`      DEFAULT NOW() at insert.
--       - `updated_at`      DEFAULT NOW() at insert; the
--                            `missions_set_updated_at` trigger
--                            refreshes it.
--       - UNIQUE (project_code, mission_kind, mission_code).

CREATE TABLE missions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_code    TEXT NOT NULL,
    mission_kind    TEXT NOT NULL,
    mission_code    TEXT NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT missions_natural_key
        UNIQUE (project_code, mission_kind, mission_code),
    CONSTRAINT missions_kind_check
        CHECK (mission_kind IN ('crf', 'sdtm', 'adam', 'tfl'))
);

CREATE OR REPLACE FUNCTION missions_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER missions_set_updated_at
    BEFORE UPDATE ON missions
    FOR EACH ROW
    EXECUTE FUNCTION missions_set_updated_at();