-- 0002_create_assignees.sql
--
-- Per-mission assignee rows. FK to `missions(id)` with
-- `ON DELETE CASCADE` so mission deletion cascades to its
-- assignees in a single DELETE.
--
--   * `assignees`
--       - `id`           surrogate primary key.
--       - `mission_id`   FK CASCADE.
--       - `user_code`    caller-chosen (no FK — user existence is
--                         enforced at the usecase via
--                         `UserLookup`, mirroring how mission /
--                         project referential integrity is
--                         resolved).
--       - `role`         text ('dev', 'qc') with CHECK.
--       - `created_at`   DEFAULT NOW() at insert.
--       - `updated_at`   refreshed by the trigger.
--       - UNIQUE (mission_id, user_code, role) — the per-mission
--         uniqueness invariant.

CREATE TABLE assignees (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mission_id   BIGINT NOT NULL REFERENCES missions(id) ON DELETE CASCADE,
    user_code    TEXT NOT NULL,
    role         TEXT NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT assignees_per_mission_unique
        UNIQUE (mission_id, user_code, role),
    CONSTRAINT assignees_role_check
        CHECK (role IN ('dev', 'qc'))
);

CREATE OR REPLACE FUNCTION assignees_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER assignees_set_updated_at
    BEFORE UPDATE ON assignees
    FOR EACH ROW
    EXECUTE FUNCTION assignees_set_updated_at();