-- 0003_create_mission_issues.sql
--
-- Mission-scoped issue tracker. Each row is one issue; the
-- `comments` jsonb column carries the append-only discussion
-- thread (each entry has `user`, `content`, `created_at`).
--
--   * `mission_issues`
--       - `id`           surrogate primary key.
--       - `mission_id`   FK CASCADE → missions(id).
--       - `target_item`  optional free-text label.
--       - `issuer`       user_code (no FK — user existence is
--                         enforced at the usecase via
--                         UserLookup, matching how the
--                         mission / assignee rows reference
--                         user_code and project_code).
--       - `description`  non-empty text (CHECK).
--       - `state`        'opened' | 'closed' (CHECK).
--       - `comments`     JSONB array (default '[]').
--       - `created_at`   DEFAULT NOW() at insert.
--       - `updated_at`   refreshed by the trigger below.

CREATE TABLE mission_issues (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mission_id   BIGINT NOT NULL REFERENCES missions(id) ON DELETE CASCADE,
    target_item  TEXT,
    issuer       TEXT NOT NULL,
    description  TEXT NOT NULL,
    state        TEXT NOT NULL DEFAULT 'opened',
    comments     JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT mission_issues_state_check
        CHECK (state IN ('opened', 'closed')),
    CONSTRAINT mission_issues_description_nonempty
        CHECK (length(btrim(description)) > 0),
    CONSTRAINT mission_issues_issuer_nonempty
        CHECK (length(btrim(issuer)) > 0)
);

CREATE INDEX mission_issues_by_mission
    ON mission_issues (mission_id);
CREATE INDEX mission_issues_by_mission_state
    ON mission_issues (mission_id, state);

CREATE OR REPLACE FUNCTION mission_issues_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER mission_issues_set_updated_at
    BEFORE UPDATE ON mission_issues
    FOR EACH ROW
    EXECUTE FUNCTION mission_issues_set_updated_at();
