-- 0002_create_auth_user_domain_identities.sql
--
-- Maps a (domain_name, hostname, sid) AD triple to a `user_code` so
-- `login_with_domain_user_info` can resolve a domain logon without a
-- password. One user can have multiple domain identities (e.g. laptop
-- + workstation), but the (user_code, domain_name, hostname, sid)
-- tuple is unique.
--
-- No FK to `users.code` — the auth schema is independent.

CREATE TABLE auth_user_domain_identities (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_code TEXT NOT NULL,
    domain_name TEXT NOT NULL,
    hostname TEXT NOT NULL,
    sid TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT auth_user_domain_identities_unique UNIQUE (user_code, domain_name, hostname, sid)
);