-- 0001_create_users.sql
--
-- Initial schema for the `users` table. Applied by the database
-- migration toolchain (sqlx migrate run / refinery / etc.) before the
-- `user` crate can be used against PostgreSQL.
--
-- Layout:
--   * `id`         - surrogate primary key, generated by default
--                    (so callers can supply a known id during seeding
--                    or `copy`-style imports).
--   * `code`       - caller-chosen stable identifier (employee id,
--                    login, etc.). Uniqueness is enforced globally.
--   * `name`       - human-readable display name.
--   * `role`       - one of `root`, `admin`, `general`. Constrained
--                    both in the application layer (Role enum +
--                    `Role::try_from`) and at the database by a
--                    CHECK so an out-of-band insert cannot smuggle
--                    an unknown value past the type system.
--   * `active`     - soft-delete flag. The `UserRepository` exposes
--                    a `deactivate` operation but never a hard
--                    `DELETE` statement.
--   * `password`   - argon2id PHC string (e.g. `$argon2id$v=19$...`).
--                    Hashing is performed by the usecase layer; this
--                    column stores the result.

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    role TEXT NOT NULL,
    active BOOLEAN NOT NULL,
    password TEXT NOT NULL,
    CONSTRAINT users_code_unique UNIQUE (code),
    CONSTRAINT users_role_check CHECK (role IN ('root', 'admin', 'general'))
);
