-- 0001_create_users.sql
--
-- Initial schema for the `users` table. Applied by the database
-- migration toolchain (sqlx migrate run / refinery / etc.) before the
-- `user` crate can be used against PostgreSQL.
--
-- Layout:
--   * `id`         - surrogate primary key, generated by default
--                    (so callers can supply a known id during seeding
--                    or `copy`-style imports).
--   * `code`       - caller-chosen stable identifier (employee id,
--                    login, etc.). Uniqueness is enforced globally.
--   * `name`       - human-readable display name.
--   * `role`       - one of `root`, `admin`, `general`. Constrained
--                    both in the application layer (Role enum +
--                    `Role::try_from`) and at the database by a
--                    CHECK so an out-of-band insert cannot smuggle
--                    an unknown value past the type system.
--   * `active`     - soft-delete flag. There is no `deactivate`
--                    operation in the `user` crate; callers can flip
--                    `active` via the generic `update` entry point.
--                    The crate never issues a hard `DELETE`.
--   * `created_at` - timestamp at which the row was inserted. Set once
--                    by `DEFAULT NOW()` and never modified afterwards.
--   * `updated_at` - timestamp of the most recent row modification.
--                    Initial value comes from `DEFAULT NOW()` and the
--                    `users_set_updated_at` trigger refreshes it on
--                    every UPDATE so callers do not have to remember
--                    to bump it.

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    role TEXT NOT NULL,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT users_code_unique UNIQUE (code),
    CONSTRAINT users_role_check CHECK (role IN ('root', 'admin', 'general'))
);

-- Auto-update `updated_at` on every row modification. The trigger
-- fires for every UPDATE; it does NOT fire on plain INSERTs (the
-- column's DEFAULT handles that) and it does NOT block the calling
-- UPDATE because the `updated_at = NEW.updated_at` assignment is
-- the trigger's only side effect before the row is written.
CREATE OR REPLACE FUNCTION users_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER users_set_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW
    EXECUTE FUNCTION users_set_updated_at();