/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './__root'
import { Route as AuthedRouteRouteImport } from './_authed/route'
import { Route as BootstrapRouteImport } from './bootstrap'
import { Route as LoginRouteImport } from './login'
import { Route as RegisterRouteImport } from './register'
import { Route as AuthedLayoutRouteRouteImport } from './_authed/_layout/route'
import { Route as AuthedLayoutIndexRouteImport } from './_authed/_layout/index'
import { Route as AuthedLayoutManagementRouteRouteImport } from './_authed/_layout/management/route'
import { Route as AuthedLayoutProjectsRouteImport } from './_authed/_layout/projects'
import { Route as AuthedLayoutSettingsRouteImport } from './_authed/_layout/settings'
import { Route as AuthedProjectProjectCodeRouteRouteImport } from './_authed/project/$projectCode/route'
import { Route as AuthedLayoutManagementUsersRouteImport } from './_authed/_layout/management/users'
import { Route as AuthedLayoutTerminologyAdamRouteImport } from './_authed/_layout/terminology/adam'
import { Route as AuthedLayoutTerminologyImportRouteImport } from './_authed/_layout/terminology/import'
import { Route as AuthedLayoutTerminologySdtmRouteImport } from './_authed/_layout/terminology/sdtm'
import { Route as AuthedProjectProjectCodeIndexRouteImport } from './_authed/project/$projectCode/index'
import { Route as AuthedProjectProjectCodeConfigurationRouteImport } from './_authed/project/$projectCode/configuration'
import { Route as AuthedProjectProjectCodeDashboardRouteImport } from './_authed/project/$projectCode/dashboard'
import { Route as AuthedLayoutTerminologyKindSearchRouteImport } from './_authed/_layout/terminology/$kind/search'
import { Route as AuthedLayoutTerminologyKindCodelistsCodelistIdRouteImport } from './_authed/_layout/terminology/$kind/codelists/$codelistId'

const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const BootstrapRoute = BootstrapRouteImport.update({
  id: '/bootstrap',
  path: '/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedLayoutRouteRoute = AuthedLayoutRouteRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedLayoutIndexRoute = AuthedLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedLayoutRouteRoute,
} as any)
const AuthedLayoutManagementRouteRoute =
  AuthedLayoutManagementRouteRouteImport.update({
    id: '/management',
    path: '/management',
    getParentRoute: () => AuthedLayoutRouteRoute,
  } as any)
const AuthedLayoutProjectsRoute = AuthedLayoutProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthedLayoutRouteRoute,
} as any)
const AuthedLayoutSettingsRoute = AuthedLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedLayoutRouteRoute,
} as any)
const AuthedProjectProjectCodeRouteRoute =
  AuthedProjectProjectCodeRouteRouteImport.update({
    id: '/project/$projectCode',
    path: '/project/$projectCode',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedLayoutManagementUsersRoute =
  AuthedLayoutManagementUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthedLayoutManagementRouteRoute,
  } as any)
const AuthedLayoutTerminologyAdamRoute =
  AuthedLayoutTerminologyAdamRouteImport.update({
    id: '/terminology/adam',
    path: '/terminology/adam',
    getParentRoute: () => AuthedLayoutRouteRoute,
  } as any)
const AuthedLayoutTerminologyImportRoute =
  AuthedLayoutTerminologyImportRouteImport.update({
    id: '/terminology/import',
    path: '/terminology/import',
    getParentRoute: () => AuthedLayoutRouteRoute,
  } as any)
const AuthedLayoutTerminologySdtmRoute =
  AuthedLayoutTerminologySdtmRouteImport.update({
    id: '/terminology/sdtm',
    path: '/terminology/sdtm',
    getParentRoute: () => AuthedLayoutRouteRoute,
  } as any)
const AuthedProjectProjectCodeIndexRoute =
  AuthedProjectProjectCodeIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedProjectProjectCodeRouteRoute,
  } as any)
const AuthedProjectProjectCodeConfigurationRoute =
  AuthedProjectProjectCodeConfigurationRouteImport.update({
    id: '/configuration',
    path: '/configuration',
    getParentRoute: () => AuthedProjectProjectCodeRouteRoute,
  } as any)
const AuthedProjectProjectCodeDashboardRoute =
  AuthedProjectProjectCodeDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthedProjectProjectCodeRouteRoute,
  } as any)
const AuthedLayoutTerminologyKindSearchRoute =
  AuthedLayoutTerminologyKindSearchRouteImport.update({
    id: '/terminology/$kind/search',
    path: '/terminology/$kind/search',
    getParentRoute: () => AuthedLayoutRouteRoute,
  } as any)
const AuthedLayoutTerminologyKindCodelistsCodelistIdRoute =
  AuthedLayoutTerminologyKindCodelistsCodelistIdRouteImport.update({
    id: '/terminology/$kind/codelists/$codelistId',
    path: '/terminology/$kind/codelists/$codelistId',
    getParentRoute: () => AuthedLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedLayoutIndexRoute
  '/bootstrap': typeof BootstrapRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/management': typeof AuthedLayoutManagementRouteRouteWithChildren
  '/project/$projectCode': typeof AuthedProjectProjectCodeRouteRouteWithChildren
  '/projects': typeof AuthedLayoutProjectsRoute
  '/settings': typeof AuthedLayoutSettingsRoute
  '/management/users': typeof AuthedLayoutManagementUsersRoute
  '/terminology/adam': typeof AuthedLayoutTerminologyAdamRoute
  '/terminology/import': typeof AuthedLayoutTerminologyImportRoute
  '/terminology/sdtm': typeof AuthedLayoutTerminologySdtmRoute
  '/project/$projectCode/configuration': typeof AuthedProjectProjectCodeConfigurationRoute
  '/project/$projectCode/dashboard': typeof AuthedProjectProjectCodeDashboardRoute
  '/project/$projectCode/': typeof AuthedProjectProjectCodeIndexRoute
  '/terminology/$kind/search': typeof AuthedLayoutTerminologyKindSearchRoute
  '/terminology/$kind/codelists/$codelistId': typeof AuthedLayoutTerminologyKindCodelistsCodelistIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthedLayoutIndexRoute
  '/bootstrap': typeof BootstrapRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/management': typeof AuthedLayoutManagementRouteRouteWithChildren
  '/projects': typeof AuthedLayoutProjectsRoute
  '/settings': typeof AuthedLayoutSettingsRoute
  '/management/users': typeof AuthedLayoutManagementUsersRoute
  '/terminology/adam': typeof AuthedLayoutTerminologyAdamRoute
  '/terminology/import': typeof AuthedLayoutTerminologyImportRoute
  '/terminology/sdtm': typeof AuthedLayoutTerminologySdtmRoute
  '/project/$projectCode/configuration': typeof AuthedProjectProjectCodeConfigurationRoute
  '/project/$projectCode/dashboard': typeof AuthedProjectProjectCodeDashboardRoute
  '/project/$projectCode': typeof AuthedProjectProjectCodeIndexRoute
  '/terminology/$kind/search': typeof AuthedLayoutTerminologyKindSearchRoute
  '/terminology/$kind/codelists/$codelistId': typeof AuthedLayoutTerminologyKindCodelistsCodelistIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/bootstrap': typeof BootstrapRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authed/_layout': typeof AuthedLayoutRouteRouteWithChildren
  '/_authed/_layout/management': typeof AuthedLayoutManagementRouteRouteWithChildren
  '/_authed/project/$projectCode': typeof AuthedProjectProjectCodeRouteRouteWithChildren
  '/_authed/_layout/projects': typeof AuthedLayoutProjectsRoute
  '/_authed/_layout/settings': typeof AuthedLayoutSettingsRoute
  '/_authed/_layout/': typeof AuthedLayoutIndexRoute
  '/_authed/_layout/management/users': typeof AuthedLayoutManagementUsersRoute
  '/_authed/_layout/terminology/adam': typeof AuthedLayoutTerminologyAdamRoute
  '/_authed/_layout/terminology/import': typeof AuthedLayoutTerminologyImportRoute
  '/_authed/_layout/terminology/sdtm': typeof AuthedLayoutTerminologySdtmRoute
  '/_authed/project/$projectCode/configuration': typeof AuthedProjectProjectCodeConfigurationRoute
  '/_authed/project/$projectCode/dashboard': typeof AuthedProjectProjectCodeDashboardRoute
  '/_authed/project/$projectCode/': typeof AuthedProjectProjectCodeIndexRoute
  '/_authed/_layout/terminology/$kind/search': typeof AuthedLayoutTerminologyKindSearchRoute
  '/_authed/_layout/terminology/$kind/codelists/$codelistId': typeof AuthedLayoutTerminologyKindCodelistsCodelistIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bootstrap'
    | '/login'
    | '/register'
    | '/management'
    | '/project/$projectCode'
    | '/projects'
    | '/settings'
    | '/management/users'
    | '/terminology/adam'
    | '/terminology/import'
    | '/terminology/sdtm'
    | '/project/$projectCode/configuration'
    | '/project/$projectCode/dashboard'
    | '/project/$projectCode/'
    | '/terminology/$kind/search'
    | '/terminology/$kind/codelists/$codelistId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bootstrap'
    | '/login'
    | '/register'
    | '/management'
    | '/projects'
    | '/settings'
    | '/management/users'
    | '/terminology/adam'
    | '/terminology/import'
    | '/terminology/sdtm'
    | '/project/$projectCode/configuration'
    | '/project/$projectCode/dashboard'
    | '/project/$projectCode'
    | '/terminology/$kind/search'
    | '/terminology/$kind/codelists/$codelistId'
  id:
    | '__root__'
    | '/_authed'
    | '/bootstrap'
    | '/login'
    | '/register'
    | '/_authed/_layout'
    | '/_authed/_layout/management'
    | '/_authed/project/$projectCode'
    | '/_authed/_layout/projects'
    | '/_authed/_layout/settings'
    | '/_authed/_layout/'
    | '/_authed/_layout/management/users'
    | '/_authed/_layout/terminology/adam'
    | '/_authed/_layout/terminology/import'
    | '/_authed/_layout/terminology/sdtm'
    | '/_authed/project/$projectCode/configuration'
    | '/_authed/project/$projectCode/dashboard'
    | '/_authed/project/$projectCode/'
    | '/_authed/_layout/terminology/$kind/search'
    | '/_authed/_layout/terminology/$kind/codelists/$codelistId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  BootstrapRoute: typeof BootstrapRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bootstrap': {
      id: '/bootstrap'
      path: '/bootstrap'
      fullPath: '/bootstrap'
      preLoaderRoute: typeof BootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_layout': {
      id: '/_authed/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedLayoutRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/_layout/': {
      id: '/_authed/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedLayoutIndexRouteImport
      parentRoute: typeof AuthedLayoutRouteRoute
    }
    '/_authed/_layout/management': {
      id: '/_authed/_layout/management'
      path: '/management'
      fullPath: '/management'
      preLoaderRoute: typeof AuthedLayoutManagementRouteRouteImport
      parentRoute: typeof AuthedLayoutRouteRoute
    }
    '/_authed/_layout/projects': {
      id: '/_authed/_layout/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthedLayoutProjectsRouteImport
      parentRoute: typeof AuthedLayoutRouteRoute
    }
    '/_authed/_layout/settings': {
      id: '/_authed/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedLayoutSettingsRouteImport
      parentRoute: typeof AuthedLayoutRouteRoute
    }
    '/_authed/project/$projectCode': {
      id: '/_authed/project/$projectCode'
      path: '/project/$projectCode'
      fullPath: '/project/$projectCode'
      preLoaderRoute: typeof AuthedProjectProjectCodeRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/_layout/management/users': {
      id: '/_authed/_layout/management/users'
      path: '/users'
      fullPath: '/management/users'
      preLoaderRoute: typeof AuthedLayoutManagementUsersRouteImport
      parentRoute: typeof AuthedLayoutManagementRouteRoute
    }
    '/_authed/_layout/terminology/adam': {
      id: '/_authed/_layout/terminology/adam'
      path: '/terminology/adam'
      fullPath: '/terminology/adam'
      preLoaderRoute: typeof AuthedLayoutTerminologyAdamRouteImport
      parentRoute: typeof AuthedLayoutRouteRoute
    }
    '/_authed/_layout/terminology/import': {
      id: '/_authed/_layout/terminology/import'
      path: '/terminology/import'
      fullPath: '/terminology/import'
      preLoaderRoute: typeof AuthedLayoutTerminologyImportRouteImport
      parentRoute: typeof AuthedLayoutRouteRoute
    }
    '/_authed/_layout/terminology/sdtm': {
      id: '/_authed/_layout/terminology/sdtm'
      path: '/terminology/sdtm'
      fullPath: '/terminology/sdtm'
      preLoaderRoute: typeof AuthedLayoutTerminologySdtmRouteImport
      parentRoute: typeof AuthedLayoutRouteRoute
    }
    '/_authed/project/$projectCode/': {
      id: '/_authed/project/$projectCode/'
      path: '/'
      fullPath: '/project/$projectCode/'
      preLoaderRoute: typeof AuthedProjectProjectCodeIndexRouteImport
      parentRoute: typeof AuthedProjectProjectCodeRouteRoute
    }
    '/_authed/project/$projectCode/configuration': {
      id: '/_authed/project/$projectCode/configuration'
      path: '/configuration'
      fullPath: '/project/$projectCode/configuration'
      preLoaderRoute: typeof AuthedProjectProjectCodeConfigurationRouteImport
      parentRoute: typeof AuthedProjectProjectCodeRouteRoute
    }
    '/_authed/project/$projectCode/dashboard': {
      id: '/_authed/project/$projectCode/dashboard'
      path: '/dashboard'
      fullPath: '/project/$projectCode/dashboard'
      preLoaderRoute: typeof AuthedProjectProjectCodeDashboardRouteImport
      parentRoute: typeof AuthedProjectProjectCodeRouteRoute
    }
    '/_authed/_layout/terminology/$kind/search': {
      id: '/_authed/_layout/terminology/$kind/search'
      path: '/terminology/$kind/search'
      fullPath: '/terminology/$kind/search'
      preLoaderRoute: typeof AuthedLayoutTerminologyKindSearchRouteImport
      parentRoute: typeof AuthedLayoutRouteRoute
    }
    '/_authed/_layout/terminology/$kind/codelists/$codelistId': {
      id: '/_authed/_layout/terminology/$kind/codelists/$codelistId'
      path: '/terminology/$kind/codelists/$codelistId'
      fullPath: '/terminology/$kind/codelists/$codelistId'
      preLoaderRoute: typeof AuthedLayoutTerminologyKindCodelistsCodelistIdRouteImport
      parentRoute: typeof AuthedLayoutRouteRoute
    }
  }
}

interface AuthedLayoutManagementRouteRouteChildren {
  AuthedLayoutManagementUsersRoute: typeof AuthedLayoutManagementUsersRoute
}

const AuthedLayoutManagementRouteRouteChildren: AuthedLayoutManagementRouteRouteChildren =
  {
    AuthedLayoutManagementUsersRoute: AuthedLayoutManagementUsersRoute,
  }

const AuthedLayoutManagementRouteRouteWithChildren =
  AuthedLayoutManagementRouteRoute._addFileChildren(
    AuthedLayoutManagementRouteRouteChildren,
  )

interface AuthedLayoutRouteRouteChildren {
  AuthedLayoutManagementRouteRoute: typeof AuthedLayoutManagementRouteRouteWithChildren
  AuthedLayoutProjectsRoute: typeof AuthedLayoutProjectsRoute
  AuthedLayoutSettingsRoute: typeof AuthedLayoutSettingsRoute
  AuthedLayoutIndexRoute: typeof AuthedLayoutIndexRoute
  AuthedLayoutTerminologyAdamRoute: typeof AuthedLayoutTerminologyAdamRoute
  AuthedLayoutTerminologyImportRoute: typeof AuthedLayoutTerminologyImportRoute
  AuthedLayoutTerminologySdtmRoute: typeof AuthedLayoutTerminologySdtmRoute
  AuthedLayoutTerminologyKindSearchRoute: typeof AuthedLayoutTerminologyKindSearchRoute
  AuthedLayoutTerminologyKindCodelistsCodelistIdRoute: typeof AuthedLayoutTerminologyKindCodelistsCodelistIdRoute
}

const AuthedLayoutRouteRouteChildren: AuthedLayoutRouteRouteChildren = {
  AuthedLayoutManagementRouteRoute:
    AuthedLayoutManagementRouteRouteWithChildren,
  AuthedLayoutProjectsRoute: AuthedLayoutProjectsRoute,
  AuthedLayoutSettingsRoute: AuthedLayoutSettingsRoute,
  AuthedLayoutIndexRoute: AuthedLayoutIndexRoute,
  AuthedLayoutTerminologyAdamRoute: AuthedLayoutTerminologyAdamRoute,
  AuthedLayoutTerminologyImportRoute: AuthedLayoutTerminologyImportRoute,
  AuthedLayoutTerminologySdtmRoute: AuthedLayoutTerminologySdtmRoute,
  AuthedLayoutTerminologyKindSearchRoute:
    AuthedLayoutTerminologyKindSearchRoute,
  AuthedLayoutTerminologyKindCodelistsCodelistIdRoute:
    AuthedLayoutTerminologyKindCodelistsCodelistIdRoute,
}

const AuthedLayoutRouteRouteWithChildren =
  AuthedLayoutRouteRoute._addFileChildren(AuthedLayoutRouteRouteChildren)

interface AuthedProjectProjectCodeRouteRouteChildren {
  AuthedProjectProjectCodeConfigurationRoute: typeof AuthedProjectProjectCodeConfigurationRoute
  AuthedProjectProjectCodeDashboardRoute: typeof AuthedProjectProjectCodeDashboardRoute
  AuthedProjectProjectCodeIndexRoute: typeof AuthedProjectProjectCodeIndexRoute
}

const AuthedProjectProjectCodeRouteRouteChildren: AuthedProjectProjectCodeRouteRouteChildren =
  {
    AuthedProjectProjectCodeConfigurationRoute:
      AuthedProjectProjectCodeConfigurationRoute,
    AuthedProjectProjectCodeDashboardRoute:
      AuthedProjectProjectCodeDashboardRoute,
    AuthedProjectProjectCodeIndexRoute: AuthedProjectProjectCodeIndexRoute,
  }

const AuthedProjectProjectCodeRouteRouteWithChildren =
  AuthedProjectProjectCodeRouteRoute._addFileChildren(
    AuthedProjectProjectCodeRouteRouteChildren,
  )

interface AuthedRouteRouteChildren {
  AuthedLayoutRouteRoute: typeof AuthedLayoutRouteRouteWithChildren
  AuthedProjectProjectCodeRouteRoute: typeof AuthedProjectProjectCodeRouteRouteWithChildren
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedLayoutRouteRoute: AuthedLayoutRouteRouteWithChildren,
  AuthedProjectProjectCodeRouteRoute:
    AuthedProjectProjectCodeRouteRouteWithChildren,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  BootstrapRoute: BootstrapRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
