-- 0001_create_projects.sql
--
-- Single migration for the `project` crate. Replaces the previous
-- two-file history (products + projects + project_members) now that
-- the `Product` aggregate has been retired and `projects` carries a
-- JSONB `tags` array.
--
-- Layout:
--   * `projects`
--       - `id`          - surrogate primary key.
--       - `code`        - caller-chosen stable identifier; unique.
--       - `description` - free-form long description. Defaults to empty.
--       - `active`      - soft-delete flag (no hard DELETE).
--       - `tags`        - JSONB array of `{"key": "...", "value": "..."}`
--                         objects. Default is the empty array.
--                         CHECK constraint enforces the array shape
--                         against direct-SQL inserts.
--       - `created_at`  - DEFAULT NOW() at insert.
--       - `updated_at`  - DEFAULT NOW() at insert; the
--                         `projects_set_updated_at` trigger refreshes it.
--
--   * `project_members`
--       - Composite PK on (project_id, team_type, role_type, user_code).
--       - `team_type`  ∈ {'members', 'unblind_members'}.
--       - `role_type`  ∈ {'leader', 'worker'}.
--       - ON DELETE CASCADE on the FK so wiping a project also wipes
--         its membership rows.

CREATE TABLE projects (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    active BOOLEAN NOT NULL DEFAULT TRUE,
    tags JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT projects_code_unique UNIQUE (code),
    CONSTRAINT projects_tags_is_array CHECK (jsonb_typeof(tags) = 'array')
);

CREATE OR REPLACE FUNCTION projects_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER projects_set_updated_at
    BEFORE UPDATE ON projects
    FOR EACH ROW
    EXECUTE FUNCTION projects_set_updated_at();

CREATE TABLE project_members (
    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    team_type TEXT NOT NULL,
    role_type TEXT NOT NULL,
    user_code TEXT NOT NULL,
    PRIMARY KEY (project_id, team_type, role_type, user_code),
    CONSTRAINT project_members_team_check
        CHECK (team_type IN ('members', 'unblind_members')),
    CONSTRAINT project_members_role_check
        CHECK (role_type IN ('leader', 'worker'))
);