-- 0001_create_products.sql
--
-- Initial schema for the `products` table. Applied by the database
-- migration toolchain (sqlx migrate run / refinery / etc.) before the
-- `project` crate can be used against PostgreSQL.
--
-- Layout:
--   * `id`          - surrogate primary key, generated by default
--                     (so callers can supply a known id during seeding
--                     or `copy`-style imports).
--   * `code`        - caller-chosen stable identifier. Uniqueness is
--                     enforced globally.
--   * `name`        - human-readable display name.
--   * `description` - free-form long description. Defaults to empty.
--   * `active`      - soft-delete flag. There is no `deactivate`
--                     operation in this crate; callers can flip
--                     `active` via the generic `update_product` entry
--                     point. The crate never issues a hard `DELETE`.
--   * `created_at`  - timestamp at which the row was inserted. Set once
--                     by `DEFAULT NOW()` and never modified afterwards.
--   * `updated_at`  - timestamp of the most recent row modification.
--                     Initial value comes from `DEFAULT NOW()` and the
--                     `products_set_updated_at` trigger refreshes it
--                     on every UPDATE.

CREATE TABLE products (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT products_code_unique UNIQUE (code)
);

-- Auto-update `updated_at` on every row modification.
CREATE OR REPLACE FUNCTION products_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER products_set_updated_at
    BEFORE UPDATE ON products
    FOR EACH ROW
    EXECUTE FUNCTION products_set_updated_at();
