-- 0002_create_projects.sql
--
-- Schema for the `projects` table and the `project_members` join
-- table. Applied after 0001 so the FK to `products(id)` is valid.
--
-- `projects`:
--   * `id`          - surrogate primary key.
--   * `code`        - caller-chosen stable identifier; unique.
--   * `description` - free-form long description. Defaults to empty.
--   * `product_id`  - FK to `products(id)`; the owning product.
--   * `active`      - soft-delete flag (no hard DELETE).
--   * `created_at`  - DEFAULT NOW() at insert.
--   * `updated_at`  - DEFAULT NOW() at insert; the
--                     `projects_set_updated_at` trigger refreshes it.
--
-- `project_members`:
--   * Composite PK on (project_id, team_type, role_type, user_code).
--   * `team_type` ∈ {'members', 'unblind_members'}.
--   * `role_type` ∈ {'leader', 'worker'}.
--   * ON DELETE CASCADE on the FK so wiping a project also wipes its
--     membership rows.

CREATE TABLE projects (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    product_id INTEGER NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT projects_code_unique UNIQUE (code),
    CONSTRAINT projects_product_fk FOREIGN KEY (product_id)
        REFERENCES products(id)
);

CREATE OR REPLACE FUNCTION projects_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER projects_set_updated_at
    BEFORE UPDATE ON projects
    FOR EACH ROW
    EXECUTE FUNCTION projects_set_updated_at();

CREATE TABLE project_members (
    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    team_type TEXT NOT NULL,
    role_type TEXT NOT NULL,
    user_code TEXT NOT NULL,
    PRIMARY KEY (project_id, team_type, role_type, user_code),
    CONSTRAINT project_members_team_check
        CHECK (team_type IN ('members', 'unblind_members')),
    CONSTRAINT project_members_role_check
        CHECK (role_type IN ('leader', 'worker'))
);
