[package]
name = "windows-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62.2", features = [
    "Win32_System_WindowsProgramming",
    "Win32_Security_Authentication_Identity",
    "Win32_System_SystemInformation",
] }
